FROM archlinux:latest

WORKDIR /home/test_user
COPY . .

RUN chmod +x create_and_switch_to_test_user.sh
# RUN chmod +x install_pacman_pkgs.sh
# RUN chmod +x add_yay.sh
# RUN chmod +x install_yay_pkgs.sh



# CMD ["./install_pacman_pkgs.sh"]
#
CMD ["tail", "-f", "/dev/null"]
